#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  4 09:47:16 2024

@author: Avery Davis Bell

Gets flanking regions for regions in a bed file, returns new bed file with these flanks as their own regions
"""
import argparse
import time

#%%
def region2flanks(strChr, iStart, iEnd, strStrand, strName, iTotal, iInner):
    """
    For one bed region, gets total flank region (5' and 3') as well as inner and outer flank regions

    Parameters
    ----------
    strChr : str
        Chromosome. Just passed through
    iStart : int
        start position of bed region (NOT corrected for strand, obligately < iEnd)
    iEnd : ind
        end position of bed region (NOT corrected for strand, obligately > iStart)
    strStrand : str
        strand: + or -
    strName : str
        name of bed region (from input)
    iTotal : int
        Total flank length to get (for whole flanking region)
    iInner : int
        length of inner flank. outside of this but inside iTotal will be outer flank
        
    Returns
    -------
    aaFlanks, list of lists of flank regions ( 5' total flank, 5' inner, 5' outer, 3' total flank, 3' inner flank, 3' outer flank,).
    Elements of each list:
            strChr
            iStart
            iEnd
            strName - original name plus name of flank (e.g. flank3, innerflank5, etc)
            strStrand
            
    """
    # Generate flanks
    ## From start side (either 5' or 3' depending on strand)
    aiTotalStart = [iStart - iTotal, iStart]
    aiInnerStart = [iStart - iInner, iStart]
    aiOuterStart = [iStart - iTotal, iStart - iInner]
    ## From end side (either 5' or 3' depending on strand)
    aiTotalEnd = [iEnd, iEnd + iTotal]
    aiInnerEnd = [iEnd, iEnd + iInner]
    aiOuterEnd = [iEnd + iInner, iEnd + iTotal]
    
    # get output name separator
    if strName=="":
        strSep = ""
    else:

        strSep = "."
    
    # Determine which is 5', 3' based on strand; combine full info
    if strStrand=="+": # on plus strand, start is 5' and end is 3'
        aiTotal5 = [strChr] + aiTotalStart + [strName + strSep + "flank_total_5" , strStrand]
        aiInner5 = [strChr] + aiInnerStart + [strName + strSep + "flank_inner_5" , strStrand]
        aiOuter5 = [strChr] + aiOuterStart + [strName + strSep + "flank_outer_5" , strStrand]
        aiTotal3 = [strChr] + aiTotalEnd + [strName + strSep + "flank_total_3" , strStrand]
        aiInner3 = [strChr] + aiInnerEnd + [strName + strSep + "flank_inner_3" , strStrand]
        aiOuter3 = [strChr] + aiOuterEnd + [strName + strSep + "flank_outer_3" , strStrand]
    elif strStrand=="-": # on minus strand, start is 3' and end is 5'
        aiTotal5 = [strChr] + aiTotalEnd + [strName + strSep + "flank_total_5" , strStrand]
        aiInner5 = [strChr] + aiInnerEnd + [strName + strSep + "flank_inner_5" , strStrand]
        aiOuter5 = [strChr] + aiOuterEnd + [strName + strSep + "flank_outer_5" , strStrand]
        aiTotal3 = [strChr] + aiTotalStart + [strName + strSep + "flank_total_3" , strStrand]
        aiInner3 = [strChr] + aiInnerStart + [strName + strSep + "flank_inner_3" , strStrand]
        aiOuter3 = [strChr] + aiOuterStart + [strName + strSep + "flank_outer_3" , strStrand]
    
    # Return
    return([aiTotal5, aiInner5, aiOuter5, aiTotal3, aiInner3, aiOuter3])
#%%
def processbed(strBed, iTotal, iInner, strOut):
    """
    Gets flank regions for each line of bed file, writes them out line-by-line

    Parameters
    ----------
    strBed : TYPE
        DESCRIPTION.
    iTotal : TYPE
        DESCRIPTION.
    iInner : TYPE
        DESCRIPTION.
    strOut : TYPE
        DESCRIPTION.

    Returns
    -------
    None.

    """
    # Open files
    istm = open(strBed)
    ostm = open(strOut, "w")
    
    # Log process that made file
    HEADER = "# Generated by bed2flanks.py starting at %s" % time.ctime()
    ostm.write(HEADER + "\n") 
    
    # Process
    for strLine in istm:
        if strLine[0]=="#":
            continue
        astrLine = strLine.strip().split("\t")
        strChr, strStart, strEnd, strName, strNum, strStrand = astrLine[0:6] # keep just key parts
        # Get flanks
        aFlanks = region2flanks(strChr, int(strStart), int(strEnd), strStrand, strName, iTotal, iInner)
        # Save out
        for flank in aFlanks:
            strChr, iStart, iEnd, strFlName, strStrand = flank
            strFlStart = str(iStart)
            strFlEnd = str(iEnd)
            ostm.write(("\t").join([strChr, strFlStart, strFlEnd, strFlName, strNum, strStrand]) + "\n")
    
    # Close files
    istm.close()
    ostm.close()

#%%
def main():
    # Parse arguments
    argp = argparse.ArgumentParser(prog = "bed2flanks.py",
                                   description = "Gets flanking regions for regions in a bed file, returns new bed file with these flanks as their own regions")
    argp.add_argument("-bed", dest = "strBed", required = True, type = str,
                      metavar = "regions.bed",
                      help = "Path to bed file containing regions for which to get flanking regions (e.g., tRNA genes)")
    argp.add_argument("-nflank", dest = "iTotal", required = True, type = int, default = 40,
                      metavar = "N",
                      help = "Length of desired total flanking region (on either side of region, not combined) in bp")
    argp.add_argument("-ninner", dest = "iInner", required = True, type = int, default = 20,
                      metavar = "N",
                      help = "Length of desired INNER flanking region (on either side of region, not combined) in bp.\
                          Bases between this and nflank will be classified as outer flanking regions")               
    argp.add_argument("-out", dest = "strOut", required = True, type = str, default = "out.bed",
                      metavar = "out.bed",
                      help = "Output file to contain flank regions bed")
    args = argp.parse_args()
    
    # Process bed file
    processbed(args.strBed, args.iTotal, args.iInner, args.strOut)

if __name__=="__main__":
	main()